# Generated by Django 3.2.12 on 2023-05-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='company profile images'),
        ),
    ]
