# Generated by Django 3.2.12 on 2023-05-24 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_company_profile_pic'),
    ]


    operations = [
        migrations.CreateModel(
            name='UpdateEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, unique=True)),
                ('email_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='individual',
            name='id_number',
        ),
        migrations.AlterField(
            model_name='individual',
            name='verification_badge',
            field=models.CharField(default='not_applied', max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
