# Generated by Django 3.2.12 on 2023-05-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230523_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, unique=True)),
                ('email_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
