# Generated by Django 3.2.12 on 2023-05-23 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.industry')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('is_top_seller', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='draft', max_length=20)),
                ('product_pics', models.ImageField(upload_to='product_images')),
                ('patent', models.ImageField(upload_to='patent_image')),
                ('engine_no', models.CharField(max_length=6)),
                ('chassis_no', models.CharField(max_length=17)),
                ('net_weight', models.FloatField(max_length=30)),
                ('power', models.FloatField(max_length=30)),
                ('displacement', models.FloatField(max_length=30)),
                ('torque', models.FloatField(max_length=30)),
                ('mixed_consumption', models.CharField(max_length=30)),
                ('transmission', models.CharField(max_length=10)),
                ('fuel', models.CharField(max_length=10)),
                ('traction', models.CharField(max_length=10)),
                ('scheduled_maintenance', models.BooleanField(null=True)),
                ('technical_visit_included', models.BooleanField(null=True)),
                ('is_insurance_verified', models.BooleanField(default=False)),
                ('supply_included', models.BooleanField(null=True)),
                ('product_condition', models.CharField(max_length=10)),
                ('has_certificate', models.BooleanField(null=True)),
                ('has_insurance', models.BooleanField(null=True)),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.city')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.industry')),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.machinetype')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.model')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.plan')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=30)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.model')),
            ],
        ),
        migrations.CreateModel(
            name='RentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.FloatField(max_length=20)),
                ('minimum_hours', models.IntegerField()),
                ('detailed', models.BooleanField()),
                ('dispatch_included', models.BooleanField()),
                ('operator_included', models.BooleanField()),
                ('maq_lease_contract', models.BooleanField()),
                ('lease_guaranteed_condition_checklist', models.BooleanField()),
                ('percentage_amount', models.IntegerField()),
                ('percentage', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='RentDetailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_1', models.IntegerField()),
                ('value_2', models.IntegerField()),
                ('value_3', models.IntegerField()),
                ('value_4', models.IntegerField()),
                ('value_5', models.IntegerField()),
                ('value_6', models.IntegerField()),
                ('value_7', models.IntegerField()),
                ('value_8', models.IntegerField()),
                ('value_9', models.IntegerField()),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.rentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_pics', models.ImageField(upload_to='product-images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.producttype')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcategories'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.label'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.producttype'),
        ),
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.region'),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.year'),
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='insurance-images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_condition', models.CharField(max_length=30)),
                ('hours_used', models.CharField(max_length=10)),
                ('km_run', models.CharField(max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.region'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('file', models.ImageField(upload_to='certificate-images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('region_id', 'city_name')},
        ),
    ]
