# Generated by Django 3.2.12 on 2023-05-27 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_pics',
        ),
        migrations.AddField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='hours_used',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='km_run',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='product_condition',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='chassis_no',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.city'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='displacement',
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='engine_no',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fuel',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_insurance_verified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mixed_consumption',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_weight',
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='patent',
            field=models.ImageField(null=True, upload_to='patent_image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='power',
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_condition',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.label'),
        ),
        migrations.AlterField(
            model_name='product',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.region'),
        ),
        migrations.AlterField(
            model_name='product',
            name='torque',
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='traction',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='transmission',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.year'),
        ),
        migrations.AlterField(
            model_name='rentinfo',
            name='detailed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='rentinfo',
            name='dispatch_included',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='rentinfo',
            name='hourly_rate',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentinfo',
            name='lease_guaranteed_condition_checklist',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='rentinfo',
            name='maq_lease_contract',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='rentinfo',
            name='minimum_hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rentinfo',
            name='operator_included',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='rentinfo',
            name='percentage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rentinfo',
            name='percentage_amount',
            field=models.IntegerField(null=True),
        ),
    ]
