# Generated by Django 3.2.12 on 2023-05-31 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20230526_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='part_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='TyresInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_width', models.IntegerField()),
                ('aspect_ratio', models.CharField(max_length=10)),
                ('tire_diameter', models.FloatField()),
                ('outside_diameter', models.FloatField()),
                ('load_index', models.FloatField()),
                ('speed_index', models.FloatField()),
                ('maximum_load', models.FloatField(null=True)),
                ('maximum_speed', models.FloatField(null=True)),
                ('utqg', models.CharField(max_length=30)),
                ('wear_rate', models.CharField(max_length=10)),
                ('traction_index', models.CharField(max_length=30, null=True)),
                ('temperature_index', models.CharField(max_length=10, null=True)),
                ('type_of_construction', models.CharField(max_length=30, null=True)),
                ('is_run_flat', models.BooleanField(null=True)),
                ('terrain_type_condition', models.CharField(max_length=30, null=True)),
                ('terrain_type_technology', models.CharField(max_length=30, null=True)),
                ('tread_design_technology', models.CharField(max_length=30, null=True)),
                ('type_of_service_condition', models.CharField(max_length=30)),
                ('vehicle_type_condition', models.CharField(max_length=30)),
                ('season_condition', models.CharField(max_length=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.size')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_included', models.BooleanField(default=False)),
                ('product_price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
